FROM node:14.17.4
RUN npm install -g @angular/cli
WORKDIR /angular
COPY . .
USER node
EXPOSE 4200 49153
# Ref.: https://itnext.io/docker-development-environment-angular-full-guide-a38ee34fb651
RUN npm install
RUN npm run dev