version: "3"

services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    image: mguizelini/nginx:prod
    container_name: nginx
    ports:
      - 80:80
      - 444:443
    restart: always
    volumes:
      # - ./:/var/www/frontend
      - ./docker/nginx:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      # - /etc/letsencrypt/live/www.parceiros.easytoque.com.br:/var/www/frontend/docker/letsencrypt
    tty: true
    networks:
      - easytoque-network
  # webserver:
  #   image: nginx:latest
  #   ports:
  #     - 80:80
  #     - 443:443
  #   restart: always
  #   volumes:
  #     - ./nginx/conf/:/etc/nginx/conf.d/:ro
  #     - ./certbot/www:/var/www/certbot/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
    tty: true
    networks:
      - easytoque-network

networks:
  easytoque-network:
    driver: bridge
