version: "3"

services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    image: mguizelini/nginx:prod
    container_name: nginx
    ports:
      - 80:80
      - 444:443
    volumes:
      # - ./:/var/www/frontend
      - ./docker/nginx:/etc/nginx/conf.d
      - /etc/letsencrypt/live/www.parceiros.easytoque.com.br:/var/www/frontend/docker/letsencrypt
    tty: true
    networks:
      - easytoque-network

networks:
  easytoque-network:
    driver: bridge
