version: '3'

services:
  nginx:
    image: nginx:1.15.0-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    tty: true
    networks:
      - easytoque-network

networks:
  easytoque-network:
    driver: bridge