FROM node:14.17.4
RUN npm install -g @angular/cli
WORKDIR /angular
COPY . .
RUN mv ./dev-entrypoint.sh /usr/local/bin/dev-entrypoint
RUN chmod 777 /usr/local/bin/dev-entrypoint
USER node
EXPOSE 4200 49153
# Ref.: https://itnext.io/docker-development-environment-angular-full-guide-a38ee34fb651
